import type { UiPlayer } from '@/lib/bookbacked/client';

export const demoPlayers: UiPlayer[] = [
  {
    rank: 1,
    slug: 'josh-allen',
    name: 'Josh Allen',
    team: 'BUF',
    opponent: 'vs NE',
    pos: 'QB',
    color: '#2458A6',
    projection: 24.8,
    coverageScore: 92,
    bookCount: 8,
    altLineCount: 0,
    markets: ['269.5', '41.5', '2.5'],
    marketLabels: ['PASS YDS', 'RUSH YDS', 'PASS TD'],
    range: '19.2–31.6',
    low: 19.2,
    high: 31.6,
    risk: 'Stable',
    anytimeTd: '+145',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 2,
    slug: 'bijan-robinson',
    name: 'Bijan Robinson',
    team: 'ATL',
    opponent: 'at CAR',
    pos: 'RB',
    color: '#C41130',
    projection: 21.7,
    coverageScore: 89,
    bookCount: 8,
    altLineCount: 0,
    markets: ['74.5', '29.5', '-135'],
    marketLabels: ['RUSH YDS', 'REC YDS', 'ANY TD'],
    range: '14.8–28.9',
    low: 14.8,
    high: 28.9,
    risk: 'Stable',
    anytimeTd: '-135',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 3,
    slug: 'jamarr-chase',
    name: 'Ja’Marr Chase',
    team: 'CIN',
    opponent: 'vs PIT',
    pos: 'WR',
    color: '#F36A22',
    projection: 20.9,
    coverageScore: 87,
    bookCount: 8,
    altLineCount: 0,
    markets: ['84.5', '6.5', '+105'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '11.7–31.2',
    low: 11.7,
    high: 31.2,
    risk: 'Ceiling',
    anytimeTd: '+105',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 4,
    slug: 'jahmyr-gibbs',
    name: 'Jahmyr Gibbs',
    team: 'DET',
    opponent: 'at GB',
    pos: 'RB',
    color: '#0076B6',
    projection: 20.1,
    coverageScore: 84,
    bookCount: 8,
    altLineCount: 0,
    markets: ['63.5', '32.5', '-115'],
    marketLabels: ['RUSH YDS', 'REC YDS', 'ANY TD'],
    range: '13.1–28.2',
    low: 13.1,
    high: 28.2,
    risk: 'Ceiling',
    anytimeTd: '-115',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 5,
    slug: 'puka-nacua',
    name: 'Puka Nacua',
    team: 'LAR',
    opponent: 'vs SEA',
    pos: 'WR',
    color: '#003594',
    projection: 19.6,
    coverageScore: 82,
    bookCount: 8,
    altLineCount: 0,
    markets: ['79.5', '6.5', '+125'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '12.4–28.1',
    low: 12.4,
    high: 28.1,
    risk: 'Volume',
    anytimeTd: '+125',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 6,
    slug: 'trey-mcbride',
    name: 'Trey McBride',
    team: 'ARI',
    opponent: 'at IND',
    pos: 'TE',
    color: '#97233F',
    projection: 16.4,
    coverageScore: 78,
    bookCount: 8,
    altLineCount: 0,
    markets: ['64.5', '5.5', '+160'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '9.8–23.6',
    low: 9.8,
    high: 23.6,
    risk: 'Stable',
    anytimeTd: '+160',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 7,
    slug: 'lamar-jackson',
    name: 'Lamar Jackson',
    team: 'BAL',
    opponent: 'vs CLE',
    pos: 'QB',
    color: '#241773',
    projection: 23.6,
    coverageScore: 77,
    bookCount: 8,
    altLineCount: 0,
    markets: ['241.5', '57.5', '1.5'],
    marketLabels: ['PASS YDS', 'RUSH YDS', 'PASS TD'],
    range: '16.8–32.4',
    low: 16.8,
    high: 32.4,
    risk: 'Ceiling',
    anytimeTd: '+120',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 8,
    slug: 'justin-jefferson',
    name: 'Justin Jefferson',
    team: 'MIN',
    opponent: 'at CHI',
    pos: 'WR',
    color: '#4F2683',
    projection: 19.1,
    coverageScore: 76,
    bookCount: 8,
    altLineCount: 0,
    markets: ['81.5', '6.5', '+130'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '10.9–28.8',
    low: 10.9,
    high: 28.8,
    risk: 'Ceiling',
    anytimeTd: '+130',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 9,
    slug: 'saquon-barkley',
    name: 'Saquon Barkley',
    team: 'PHI',
    opponent: 'vs NYG',
    pos: 'RB',
    color: '#004C54',
    projection: 19,
    coverageScore: 75,
    bookCount: 8,
    altLineCount: 0,
    markets: ['79.5', '19.5', '-125'],
    marketLabels: ['RUSH YDS', 'REC YDS', 'ANY TD'],
    range: '12.8–25.4',
    low: 12.8,
    high: 25.4,
    risk: 'Stable',
    anytimeTd: '-125',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 10,
    slug: 'brock-bowers',
    name: 'Brock Bowers',
    team: 'LV',
    opponent: 'at DEN',
    pos: 'TE',
    color: '#111111',
    projection: 14.8,
    coverageScore: 73,
    bookCount: 8,
    altLineCount: 0,
    markets: ['58.5', '5.5', '+190'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '8.7–21.9',
    low: 8.7,
    high: 21.9,
    risk: 'Volume',
    anytimeTd: '+190',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 11,
    slug: 'ceedee-lamb',
    name: 'CeeDee Lamb',
    team: 'DAL',
    opponent: 'vs WAS',
    pos: 'WR',
    color: '#041E42',
    projection: 18.7,
    coverageScore: 71,
    bookCount: 8,
    altLineCount: 0,
    markets: ['76.5', '6.5', '+135'],
    marketLabels: ['REC YDS', 'CATCHES', 'ANY TD'],
    range: '10.3–28.5',
    low: 10.3,
    high: 28.5,
    risk: 'Ceiling',
    anytimeTd: '+135',
    kickoff: 'Sample slate',
    source: 'demo',
  },
  {
    rank: 12,
    slug: 'breece-hall',
    name: 'Breece Hall',
    team: 'NYJ',
    opponent: 'at MIA',
    pos: 'RB',
    color: '#125740',
    projection: 17.4,
    coverageScore: 68,
    bookCount: 8,
    altLineCount: 0,
    markets: ['59.5', '27.5', '+120'],
    marketLabels: ['RUSH YDS', 'REC YDS', 'ANY TD'],
    range: '10.6–24.9',
    low: 10.6,
    high: 24.9,
    risk: 'Volume',
    anytimeTd: '+120',
    kickoff: 'Sample slate',
    source: 'demo',
  },
];

export const lineupRows = [
  {
    slot: 'QB',
    current: 'Josh Allen',
    balanced: 'Josh Allen',
    floor: 'Josh Allen',
    ceiling: 'Lamar Jackson',
  },
  {
    slot: 'RB',
    current: 'Bijan Robinson',
    balanced: 'Bijan Robinson',
    floor: 'Bijan Robinson',
    ceiling: 'Bijan Robinson',
  },
  {
    slot: 'RB',
    current: 'Breece Hall',
    balanced: 'Jahmyr Gibbs',
    floor: 'Saquon Barkley',
    ceiling: 'Jahmyr Gibbs',
  },
  {
    slot: 'WR',
    current: 'Ja’Marr Chase',
    balanced: 'Ja’Marr Chase',
    floor: 'Puka Nacua',
    ceiling: 'Ja’Marr Chase',
  },
  {
    slot: 'WR',
    current: 'CeeDee Lamb',
    balanced: 'Justin Jefferson',
    floor: 'Justin Jefferson',
    ceiling: 'CeeDee Lamb',
  },
  {
    slot: 'TE',
    current: 'Brock Bowers',
    balanced: 'Trey McBride',
    floor: 'Trey McBride',
    ceiling: 'Trey McBride',
  },
  {
    slot: 'FLEX',
    current: 'Puka Nacua',
    balanced: 'Puka Nacua',
    floor: 'Puka Nacua',
    ceiling: 'Justin Jefferson',
  },
];
